// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJR8qKrSLAT1gsLZmfMzYmvX0g83KSHNY',
    appId: '1:663924677150:web:da51ec472ebfd0954f2c0f',
    messagingSenderId: '663924677150',
    projectId: 'herbalens-firebase',
    authDomain: 'herbalens-firebase.firebaseapp.com',
    storageBucket: 'herbalens-firebase.appspot.com',
    measurementId: 'G-PF9PMWZZDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA37T6CyxnEGAhzloMXNlSOKWRlcE2MLSs',
    appId: '1:663924677150:android:dd24cbc98b9ed6454f2c0f',
    messagingSenderId: '663924677150',
    projectId: 'herbalens-firebase',
    storageBucket: 'herbalens-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-bTruPK9mqFPn_voNWFtrcYeSMUEm0tQ',
    appId: '1:663924677150:ios:f48df381bd9c06044f2c0f',
    messagingSenderId: '663924677150',
    projectId: 'herbalens-firebase',
    storageBucket: 'herbalens-firebase.appspot.com',
    iosBundleId: 'com.example.herbalens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-bTruPK9mqFPn_voNWFtrcYeSMUEm0tQ',
    appId: '1:663924677150:ios:078a4d356a3ac9094f2c0f',
    messagingSenderId: '663924677150',
    projectId: 'herbalens-firebase',
    storageBucket: 'herbalens-firebase.appspot.com',
    iosBundleId: 'com.example.herbalens.RunnerTests',
  );
}
